# Languages
#   Create a section for each of your site's languages.
#   Documentation: https://wowchemy.com/docs/guide/language/

# Default language
en:
  languageCode: en-gb
  # Uncomment for multi-lingual sites, and move English content into `en` sub-folder.
  contentDir: content/en

# Uncomment the lines below to configure your website in a second language.
ja:
  languageCode: ja-jp
  contentDir: content/ja
  title: 仙台ワイワム
  params:
    description: 神を知り、神を知らせる
  menu:
    main:
      - name: DTS
        url: '/dts'
        weight: 10
      - name: 参加する
        url: '/get-involved'
        weight: 20
      - name: ワイワムについて
        identifier: about
        weight: 30
      - name: ワイワムとは
        parent: about
        url: '/who'
        weight: 10
      - name: ビジョン
        parent: about
        url: '/vision'
        weight: 20
      - name: ブログ
        parent: about
        url: 'https://www.medium.com/ywamsendai'
        weight: 30
      - name: お問い合わせ
        parent: about
        url: '#contact'
        weight: 40
      - name: 献金
        url: '/donate'
        weight: 40
      - name: ハンドブック
        url: 'https://docs.ywamsendai.org/ja/'
        weight: 50
