# Languages
#   Create a section for each of your site's languages.
#   Documentation: https://wowchemy.com/docs/guide/language/

# Default language
en:
  languageCode: en-gb
  # Uncomment for multi-lingual sites, and move English content into `en` sub-folder.
  contentDir: content/en

# Uncomment the lines below to configure your website in a second language.
ja:
  languageCode: ja-jp
  contentDir: content/ja
  title: 仙台ワイワム
  params:
    description: 神を知り、神を知らせる
  menu:
    main:
      - name: 参加する
        url: '/get-involved'
        weight: 20
      - name: ワイワムとは
        url: '/who'
        weight: 30
      - name: ニュース
        url: 'https://www.medium.com/ywamsendai'
        weight: 40
      - name: お問い合わせ
        url: '#contact'
        weight: 50
      - name: 献金
        url: '/donate'
        weight: 60
      - name: ワイワマーへ（英語）
        url: 'https://wiki.ywamsendai.jp'
        weight: 70
